packages:
  - "apps/*"
  - "libs/*"
  - "connectors/*"
  - "tools/*"
  - "packages/*"

autoInstallPeers: true
allowBuilds:
  nx: true
  unrs-resolver: true
minimumReleaseAgeExclude:
  - '@nx/devkit@23.1.1'
  - '@nx/js@23.1.1'
  - '@nx/nx-darwin-arm64@23.1.1'
  - '@nx/nx-darwin-x64@23.1.1'
  - '@nx/nx-freebsd-x64@23.1.1'
  - '@nx/nx-linux-arm-gnueabihf@23.1.1'
  - '@nx/nx-linux-arm64-gnu@23.1.1'
  - '@nx/nx-linux-arm64-musl@23.1.1'
  - '@nx/nx-linux-x64-gnu@23.1.1'
  - '@nx/nx-linux-x64-musl@23.1.1'
  - '@nx/nx-win32-arm64-msvc@23.1.1'
  - '@nx/nx-win32-x64-msvc@23.1.1'
  - '@nx/workspace@23.1.1'
  - nx@23.1.1
